"""create decisions table

Revision ID: 22ac86ea7f8e
Revises: a76c86884834
Create Date: 2026-09-17 17:17:46.921872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ac86ea7f8e'
down_revision: Union[str, Sequence[str], None] = 'a76c86884834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_exam_id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_dimension', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_exam_id'], ['candidate_exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_candidate_exam_id'), 'decisions', ['candidate_exam_id'], unique=False)
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_candidate_exam_id'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
