"""add dimensions to evidences

Revision ID: 4faa4aeb4710
Revises: d03d672a382e
Create Date: 2026-09-13 14:14:24.999594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4faa4aeb4710'
down_revision: Union[str, Sequence[str], None] = 'd03d672a382e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidences', sa.Column('dimension', sa.String(length=150), nullable=True))
    op.add_column('evidences', sa.Column('metric', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_evidences_dimension'), 'evidences', ['dimension'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidences_dimension'), table_name='evidences')
    op.drop_column('evidences', 'metric')
    op.drop_column('evidences', 'dimension')
    # ### end Alembic commands ###
