"""create recommended actions table

Revision ID: 9efec0a5fff8
Revises: 22ac86ea7f8e
Create Date: 2026-09-17 20:20:49.390722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efec0a5fff8'
down_revision: Union[str, Sequence[str], None] = '22ac86ea7f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('operational_action', sa.String(length=150), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommended_actions_created_at'), 'recommended_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommended_actions_decision_id'), 'recommended_actions', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommended_actions_decision_id'), table_name='recommended_actions')
    op.drop_index(op.f('ix_recommended_actions_created_at'), table_name='recommended_actions')
    op.drop_table('recommended_actions')
    # ### end Alembic commands ###
